// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpvpcpexudcvmcbzulus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdnBjcGV4dWRjdm1jYnp1bHVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTU5MzgsImV4cCI6MjA2NDI5MTkzOH0.b1-lIMJ3Iv9L8_GiKUb3qbgcLU-imP3zBSRuKtE5gAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);